default: &default
  adapter: <%= ENV['ADAPTER'] %>
  encoding: <%= ENV['ENCODING'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: <%= ENV['SOCKET'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
